name: card_detector
version: 2.1.0

port: 8080

tmp_folder: ./tmp
storage_folder: ./storage
path_profession_list: ../config/professions.txt
path_company_list: ../config/companies.txt
path_names_list: ../config/names.txt

paddleocr:
  #  run_path: ./internal/service/text_recognize/paddleocr/run.py
  run_path: ../python/run_onnx_rapidocr.py
  model_rec_path: ../lib/paddleocr/onnx/en_PP-OCRv4_rec_infer.onnx
  model_det_path: ../lib/paddleocr/onnx/ch_PP-OCRv4_det_infer.onnx # detection good

log:
  level: info
  time: true

debug: true