name: card_detector
version: 3.0.8

port: 8080

tmp_folder: ./tmp
storage_folder: ./storage
path_profession_list: ./config/professions.txt
path_company_list: ./config/companies.txt
path_names_list: ./config/names.txt

paddleocr:
#  run_path: ./internal/service/text_recognize/paddleocr/run.py
  run_path: ./python/run_onnx_rapidocr.py
  model_rec_path: ./lib/paddleocr/onnx/en_PP-OCRv4_rec_infer.onnx
  model_det_path: ./lib/paddleocr/onnx/ch_PP-OCRv4_det_infer.onnx

img:
  paddle:
    size: 1800
    jpeg_quality: 87

onnx:
  path_runtime: ./lib/onnx_18/libonnxruntime.so
  path_model: ./lib/models/yolov8m-card-detect-60.onnx

log:
  level: info
  time: true

debug: true

